version: '3.7'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <suasenha>
    ports:
      - 3306:3306
    networks:
      - net-mysql
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  net-mysql:
    driver: bridge

volumes:
  mysql_data: